name: RunsafeVanishNoPacketBridge
version: 1.0.@BUILD@
description: MessageService plugin to ask VanishNoPacket about stuff
author: mortenn
main: no.runsafe.vanishbridge.Plugin
database: false
depend: [VanishNoPacket]
commands:
  fakequit:
    description: Fakes a quit event and vanishes
    aliases: [fq]
  fakejoin:
    description: Fakes a join event and unvanishes
    aliases: [fj]